"""empty message

Revision ID: 2cd94f85dc75
Revises: 8782337f5d18
Create Date: 2026-05-12 04:49:33.816509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cd94f85dc75'
down_revision: Union[str, Sequence[str], None] = '8782337f5d18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('chunk_document_id_fkey'), 'chunk', type_='foreignkey')
    op.drop_constraint(op.f('chunk_department_id_fkey'), 'chunk', type_='foreignkey')
    op.create_foreign_key(None, 'chunk', 'department', ['department_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'chunk', 'document', ['document_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('document_department_id_fkey'), 'document', type_='foreignkey')
    op.create_foreign_key(None, 'document', 'department', ['department_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'document', type_='foreignkey')
    op.create_foreign_key(op.f('document_department_id_fkey'), 'document', 'department', ['department_id'], ['id'])
    op.drop_constraint(None, 'chunk', type_='foreignkey')
    op.drop_constraint(None, 'chunk', type_='foreignkey')
    op.create_foreign_key(op.f('chunk_department_id_fkey'), 'chunk', 'department', ['department_id'], ['id'])
    op.create_foreign_key(op.f('chunk_document_id_fkey'), 'chunk', 'document', ['document_id'], ['id'])
    # ### end Alembic commands ###
