"""update chunk table

Revision ID: 6da9a3acf685
Revises: 9579309c9fd7
Create Date: 2026-05-11 06:13:36.898177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6da9a3acf685'
down_revision: Union[str, Sequence[str], None] = '9579309c9fd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunk', sa.Column('department_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'chunk', 'department', ['department_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chunk', type_='foreignkey')
    op.drop_column('chunk', 'department_id')
    # ### end Alembic commands ###
