"""update chunk table

Revision ID: a8bd44b903f6
Revises: 6da9a3acf685
Create Date: 2026-05-11 06:15:34.800503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8bd44b903f6'
down_revision: Union[str, Sequence[str], None] = '6da9a3acf685'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chunk_document_id'), table_name='chunk')
    op.create_index(op.f('ix_chunk_department_id'), 'chunk', ['department_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chunk_department_id'), table_name='chunk')
    op.create_index(op.f('ix_chunk_document_id'), 'chunk', ['document_id'], unique=False)
    # ### end Alembic commands ###
